export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';
export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART';
export const SET_ITEMS = 'SET_ITEMS';
export const FETCH_ITEMS_FAILED = 'FETCH_ITEMS_FAILED';

export const QUANTITY_INCREASE = 'QUANTITY_INCREASE';
export const QUANTITY_DECREASE = 'QUANTITY_DECREASE';

export const ORDER_INVOICE_SUMMARY = 'ORDER_INVOICE_SUMMARY';

export const USER_ORDERS = 'USER_ORDERS';

export const PURCHASE_SUCCESS = 'PURCHASE_SUCCESS';
export const PURCHASE_FAIL = 'PURCHASE_FAIL';
export const PURCHASE_START = 'PURCHASE_START';
export const PURCHASE_INIT = 'PURCHASE_INIT';

export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';
